language: python
python:
  - "2.6"
  - "2.7"
env:
  - PYTHONPATH='.'
branches:
  only:
    - master
    - next
install:
  - pip install gunicorn
  - pip install -r requirements.txt --use-mirrors
  - pip install pep8 --use-mirrors
before_script:
  - pep8 --repeat --show-source --ignore=E125 --statistics --exclude *compat*,resources.py, pecan setup.py
script: python setup.py test --functional
